#!/bin/bash
set -e
set -o pipefail

# =============================================================================
# AWS Agent Platform — CI End-to-End Test Runner
# =============================================================================
# Runs the full lifecycle in CI: install the entire platform (CI_MODE),
# run all five test-webhook.sh scenarios against it, then destroy it.
# Destroy is guaranteed via an EXIT trap even if install or tests fail,
# so a failed CI run never leaves billable infrastructure behind.
#
# Designed to run inside GitHub Actions with OIDC-assumed AWS credentials
# already in the environment. NOT for local/manual use — use install.sh,
# test-webhook.sh, and destroy.sh directly instead.
#
# Required environment variables:
#   CI_ANTHROPIC_API_KEY  — Anthropic API key for the test install
#   CI_DOMAIN_NAME        — Domain with a pre-validated ACM CNAME in DNS
#                           (e.g. revenue-growth.ai)
# Optional:
#   CI_PROJECT_NAME       — default: citest
#   CI_AGENT_NAME         — default: testagent
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

CI_PROJECT_NAME="${CI_PROJECT_NAME:-citest}"
CI_AGENT_NAME="${CI_AGENT_NAME:-testagent}"

if [ -z "${CI_ANTHROPIC_API_KEY:-}" ]; then
  echo "ERROR: CI_ANTHROPIC_API_KEY is not set."
  exit 1
fi
if [ -z "${CI_DOMAIN_NAME:-}" ]; then
  echo "ERROR: CI_DOMAIN_NAME is not set."
  exit 1
fi

AWS_REGION="${AWS_REGION:-us-east-2}"
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

echo "=================================================="
echo " CI E2E Test — install / test / destroy"
echo "=================================================="
echo ""
echo "  Project:  $CI_PROJECT_NAME"
echo "  Agent:    $CI_AGENT_NAME"
echo "  Domain:   $CI_DOMAIN_NAME"
echo "  Account:  $AWS_ACCOUNT_ID"
echo "  Region:   $AWS_REGION"
echo ""

# ------------------------------------------------------------------------------
# Write defaults.env (normally produced interactively by install.sh)
# ------------------------------------------------------------------------------

cat > "$SCRIPT_DIR/defaults.env" << EOF
# Auto-generated by ci-e2e-test.sh
PROJECT_NAME="$CI_PROJECT_NAME"
ENVIRONMENT="prod"
DOMAIN_NAME="$CI_DOMAIN_NAME"
ALLOWED_CIDR="0.0.0.0/0"
DEPLOYMENT_ROLE_ARN="arn:aws:iam::${AWS_ACCOUNT_ID}:role/terraform-deploy"
AWS_REGION="$AWS_REGION"
COST_CENTER="ci-testing"
OWNER="github-actions"
CRM_TYPE="hubspot"
ADMIN_IP=""
EOF

echo "  ✓ defaults.env written"
echo ""

# ------------------------------------------------------------------------------
# Webhook secret (normally created by install.sh)
# ------------------------------------------------------------------------------

WEBHOOK_SECRET=$(openssl rand -hex 32)
aws ssm put-parameter \
  --name "/${CI_PROJECT_NAME}/prod/orchestrator/webhook_secret" \
  --value "$WEBHOOK_SECRET" \
  --type SecureString \
  --overwrite \
  --region "$AWS_REGION" > /dev/null
echo "  ✓ Webhook secret stored in SSM"
echo ""

# ------------------------------------------------------------------------------
# Guaranteed teardown — runs on every exit path. destroy.sh in CI_MODE.
# ------------------------------------------------------------------------------

INSTALL_STARTED=false

teardown() {
  set +e
  if [ "$INSTALL_STARTED" = "true" ]; then
    echo ""
    echo "=================================================="
    echo " Teardown (always runs — even on failure)"
    echo "=================================================="
    CI_MODE=true bash "$SCRIPT_DIR/destroy.sh"
    DESTROY_EXIT=$?
    if [ "$DESTROY_EXIT" -ne 0 ]; then
      echo ""
      echo "::error::destroy.sh exited nonzero ($DESTROY_EXIT) — resources may remain in account $AWS_ACCOUNT_ID. Check the AWS console."
    fi
  fi
  # Always remove the CI webhook secret parameter (created above, outside install)
  aws ssm delete-parameter \
    --name "/${CI_PROJECT_NAME}/prod/orchestrator/webhook_secret" \
    --region "$AWS_REGION" > /dev/null 2>&1
}
trap teardown EXIT

# ------------------------------------------------------------------------------
# Install
# ------------------------------------------------------------------------------

echo "=================================================="
echo " Phase 1/3 — Install (CI_MODE)"
echo "=================================================="
INSTALL_STARTED=true
CI_MODE=true \
CI_ANTHROPIC_API_KEY="$CI_ANTHROPIC_API_KEY" \
CI_AGENT_COUNT=1 \
CI_AGENT_NAME="$CI_AGENT_NAME" \
bash "$SCRIPT_DIR/master-setup.sh"

echo ""
echo "  ✓ Install complete"

# ------------------------------------------------------------------------------
# Run all five scenarios. Continue through failures so a single failing
# scenario still lets the rest report — then fail the job at the end.
# ------------------------------------------------------------------------------

echo ""
echo "=================================================="
echo " Phase 2/3 — Test scenarios"
echo "=================================================="

SCENARIOS=(happy malformed wrong-event-type unauthorized agent-timeout)
declare -A RESULTS
OVERALL_EXIT=0

for S in "${SCENARIOS[@]}"; do
  echo ""
  echo "--------------------------------------------------"
  echo " Scenario: $S"
  echo "--------------------------------------------------"
  set +e
  bash "$SCRIPT_DIR/test-webhook.sh" --scenario "$S"
  S_EXIT=$?
  set -e
  if [ "$S_EXIT" -eq 0 ]; then
    RESULTS[$S]="PASS"
  else
    RESULTS[$S]="FAIL"
    OVERALL_EXIT=1
  fi
done

echo ""
echo "=================================================="
echo " Scenario results"
echo "=================================================="
for S in "${SCENARIOS[@]}"; do
  echo "  ${RESULTS[$S]}  $S"
  if [ "${RESULTS[$S]}" = "FAIL" ]; then
    echo "::error::Scenario '$S' FAILED"
  fi
done
echo ""

# Phase 3/3 (destroy) runs via the EXIT trap above.
echo "Phase 3/3 — Destroy will run via exit trap..."
exit $OVERALL_EXIT
